# Generated by Django 5.2.4 on 2025-11-08 14:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FragranceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('note_type', models.CharField(choices=[('top', 'Top Note'), ('heart', 'Heart Note'), ('base', 'Base Note')], max_length=5)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'note_type')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('volume_ml', models.PositiveIntegerField(help_text='Volume in volume_mls (ml)')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_notes', models.ManyToManyField(blank=True, limit_choices_to={'note_type': 'base'}, related_name='products_as_base', to='products.fragrancenote')),
                ('heart_notes', models.ManyToManyField(blank=True, limit_choices_to={'note_type': 'heart'}, related_name='products_as_heart', to='products.fragrancenote')),
                ('top_notes', models.ManyToManyField(blank=True, limit_choices_to={'note_type': 'top'}, related_name='products_as_top', to='products.fragrancenote')),
            ],
        ),
    ]
