# Generated by Django 5.2.4 on 2025-07-26 14:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Polos', 'Polos'), ('Shirts', 'Shirts'), ('Jackets', 'Jackets'), ('Hoodies', 'Hoodies'), ('Sweatshirts', 'Sweatshirts'), ('Cargos', 'Cargos'), ('Jeans', 'Jeans'), ('Shorts', 'Shorts'), ('Pants', 'Pants')], default='T-Shirts', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
