# Generated by Django 5.2.4 on 2025-11-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume_ml',
            field=models.PositiveIntegerField(help_text='Volume in milliliters (ml)'),
        ),
    ]
