# Generated by Django 5.2.4 on 2025-11-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
