# Generated by Django 5.2.4 on 2025-11-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_shipping_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_label_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_partner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('returned', 'Returned')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_order_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
