# Generated by Django 5.2.4 on 2025-11-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_shiprocket_fields'),
        ('payments', '0004_add_webhook_fields'),
    ]

    operations = [
    ]
